// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AzureIcon: typeof import('./src/components/icons/providers/AzureIcon.vue')['default']
    CenteredIcon: typeof import('./src/components/icons/CenteredIcon.vue')['default']
    DiscordIcon: typeof import('./src/components/icons/providers/DiscordIcon.vue')['default']
    EmailIcon: typeof import('./src/components/icons/providers/EmailIcon.vue')['default']
    FacebookIcon: typeof import('./src/components/icons/providers/FacebookIcon.vue')['default']
    GithubIcon: typeof import('./src/components/icons/providers/GithubIcon.vue')['default']
    GoogleIcon: typeof import('./src/components/icons/providers/GoogleIcon.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ProviderIcon: typeof import('./src/components/icons/ProviderIcon.vue')['default']
    PwaNotification: typeof import('./src/components/PwaNotification.vue')['default']
    SpotifyIcon: typeof import('./src/components/icons/providers/SpotifyIcon.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TwitchIcon: typeof import('./src/components/icons/providers/TwitchIcon.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/providers/TwitterIcon.vue')['default']
  }
}

export { }
